### ISSUE TITLE
Docker enable hostname and port endpoint. Add timeout if no mysql conn. Optimize image size

### ISSUE THREAD

**Issue by cesarjorgemartinez** [telefonicaid/fiware-keypass#104]
- Docker enable hostname and port endpoint. Cases (optional port): -dbhost hostname[:port]
- Add optional timeout DBTIMEOUT if no mysql connection. Default to 60 seconds
- Optimize image size

Uploaded fix to dockerhub with tag fixissue104

Docker compose file tests:
```yml
mysql:
  image: mysql
  expose:
    - "3306"
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: keypass
    MYSQL_DATABASE: keypass
    MYSQL_USER: keypass
    MYSQL_PASSWORD: keypass

keypass:
  image: telefonicaiot/fiware-keypass:fixissue104
  links:
    - mysql
  expose:
    - "7070"
    - "7071"
  ports:
    - "7070:7070"
    - "7071:7071"
  command: -dbhost mysql[:3306]
[  environment:
    - DBTIMEOUT=200]
```
